import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import ClientProvider from "@/components/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MegStorm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClientProvider>
        <body className={inter.className}>
          <main className="wrapper font-[Inter]">
            <Navbar />
            {children}
          </main>
        </body>
      </ClientProvider>
    </html>
  );
}
